---
title: "DIG Report"
author: "Mihir Chachar & Riya Veer"
date: "2025-11-28"
output: github_document
---

```{r}
if (!require("janitor")) install.packages("janitor")
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("lubridate")) install.packages("lubridate")
if (!require("shinydashboard")) install.packages("shinydashboard")
if (!require("shiny")) install.packages("shiny")
if (!require("reshape2")) install.packages("reshape2")
if (!require("DT")) install.packages("DT")
if (!require("plotly")) install.packages("plotly")
if (!require("visNetwork")) install.packages("visNetwork")
if (!require("rsconnect")) install.packages("rsconnect")

library(tidyverse)
library(janitor)
library(lubridate)
library(shiny)
library(shinydashboard)
library(reshape2)
library(DT)
library(plotly)
library(visNetwork)
library(rsconnect)

```

```{r}

# reading the provided dig.csv file
df <- read.csv("DIG.csv") %>%
  janitor::clean_names()

# selecting the desired variables from the trial data
df <- df %>%
  select(id, trtmt, age, race, sex, ejf_per, chestx, bmi, klevel, creat, digdoser, elevjvp, pedema, restdys, exertdys, actlimit, pulcong, heartrte, diabp, sysbp, prevmi, angina, diabetes, hyperten, diguse, diuretk, diuret, ksupp, aceinhib, nitrates, hydral, vasod, digdose, cvd, whf, mi, uang, strk, sva, vena, crev, ocvd, rinf, oth, hosp, hospdays, nhosp, death, deathday) %>%

#mutate the selected variables into character, factor & numeric    
  mutate(                      
    id = as.character(id),
    trtmt = as.factor(trtmt),
    age = as.numeric(age),
    race = as.factor(race),
    sex = as.factor(sex),
    ejf_per = as.numeric(ejf_per),
    chestx = as.numeric(chestx),
    bmi = as.numeric(bmi),
    klevel = as.numeric(klevel),
    creat = as.numeric(creat),
    digdoser = as.numeric(digdoser),
    elevjvp = as.factor(elevjvp),
    pedema = as.factor(pedema),
    restdys = as.factor(restdys),
    exertdys = as.factor(exertdys),
    actlimit = as.factor(actlimit),
    pulcong = as.factor(pulcong),
    heartrte = as.numeric(heartrte),
    diabp = as.numeric(diabp),
    sysbp = as.numeric(sysbp),
    prevmi = as.factor(prevmi),
    angina = as.factor(angina),
    diabetes = as.factor(diabetes),
    hyperten = as.factor(hyperten),
    diguse = as.factor(diguse),
    diuretk = as.factor(diuretk),
    diuret = as.factor(diuret),
    ksupp = as.factor(ksupp),
    aceinhib = as.factor(aceinhib),
    nitrates = as.factor(nitrates),
    hydral = as.factor(hydral),
    vasod = as.factor(vasod),
    digdose = as.numeric(digdose),
    cvd = as.factor(cvd),
    whf = as.factor(whf),
    mi = as.factor(mi),
    uang = as.factor(uang),
    strk = as.factor(strk),
    sva = as.factor(sva),
    vena = as.factor(vena),
    crev = as.factor(crev),
    ocvd = as.factor(ocvd),
    rinf = as.factor(rinf),
    oth = as.factor(oth),
    hosp = as.factor(hosp),
    hospdays = as.numeric(hospdays),
    nhosp = as.numeric(nhosp),
    death = as.factor(death),
    deathday = as.numeric(deathday))

# mutate the factor variables into their appropriate labels
df <- df %>%
  mutate(
    Treatment = factor(trtmt, levels = c(0, 1), labels = c("Placebo", "Digoxin")),
    Race = factor(race, levels = c(1, 2), labels = c("White", "Non-white")),
    Sex = factor(sex, levels = c(1, 2), labels = c("Male", "Female")),
    ElevatedJVP = factor(elevjvp, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Pedema = factor(pedema, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Dyspnea_at_rest = factor(restdys, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Dyspnea_on_exertion = factor(exertdys, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Action_limitation = factor(actlimit, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Pulmonary_congestion = factor(pulcong, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Prior_MI = factor(prevmi, levels = c(0, 1), labels = c("No", "Yes")),
    Angina = factor(angina, levels = c(0, 1), labels = c("No", "Yes")),
    Diabetes = factor(diabetes, levels = c(0, 1), labels = c("No", "Yes")),
    HTN = factor(hyperten, levels = c(0, 1), labels = c("No", "Yes")),
    On_Digoxin = factor(diguse, levels = c(0, 1), labels = c("No", "Yes")),
    On_Ksparing = factor(diuretk, levels = c(0, 1), labels = c("No", "Yes")),
    On_Diuretic = factor(diuret, levels = c(0, 1), labels = c("No", "Yes")),
    On_Ksupp = factor(ksupp, levels = c(0, 1), labels = c("No", "Yes")),
    On_ACE = factor(aceinhib, levels = c(0, 1), labels = c("No", "Yes")),
    On_Nitrates = factor(nitrates, levels = c(0, 1), labels = c("No", "Yes")),
    On_Hydralazine = factor(hydral, levels = c(0, 1), labels = c("No", "Yes")),
    On_Vasodilator = factor(vasod, levels = c(0, 1), labels = c("No", "Yes")),
    CVD = factor(cvd, levels = c(0, 1), labels = c("No", "Yes")),
    WHF = factor(whf, levels = c(0, 1), labels = c("No", "Yes")),
    MI = factor(mi, levels = c(0, 1), labels = c("No", "Yes")),
    Unstable_Angina = factor(uang, levels = c(0, 1), labels = c("No", "Yes")),
    Stroke = factor(strk, levels = c(0, 1), labels = c("No", "Yes")),
    Supraventricular_Arrhythmia = factor(sva, levels = c(0, 1), labels = c("No", "Yes")),
    Ventricular_Arrythmia = factor(vena, levels = c(0, 1), labels = c("No", "Yes")),
    Coronary_Revasc = factor(crev, levels = c(0, 1), labels = c("No", "Yes")),
    Other_CVD = factor(ocvd, levels = c(0, 1), labels = c("No", "Yes")),
    Respiratory_infection = factor(rinf, levels = c(0, 1), labels = c("No", "Yes")),
    Other_noncardiac = factor(oth, levels = c(0, 1), labels = c("No", "Yes")),
    Hospitalization = factor(hosp, levels = c(0, 1), labels = c("No", "Yes")),
    Death = factor(death, levels = c(0, 1), labels = c("Alive", "Dead"))) %>%
# Renaming the variables for clear indication
   rename(
    ID = id,
    Age = age,
    Prescribed_dose = digdose,
    Recommended_Dig_dose = digdoser, 
    BMI = bmi,
    EF_percent = ejf_per,
    ChestXR_ratio = chestx,
    Heart_rate = heartrte,
    Diastolic_BP = diabp,
    Systolic_BP = sysbp,
    Hospital_days = hospdays,
    No.of_Hosp = nhosp,
    Death_or_Hosp_WHF = deathday,
    )

# ------------------------------------------------------------------------------------------------------------------

# starting with the shiny app development

library(shinydashboard)


# this is created for bar plot of symptoms (specific subset)
df <- df %>%
  mutate(
    ElevatedJVP = factor(elevjvp, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Pedema = factor(pedema, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Dyspnea_at_rest = factor(restdys, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Dyspnea_on_exertion = factor(exertdys, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Action_limitation = factor(actlimit, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe")),
    Pulmonary_congestion = factor(pulcong, levels = c(0, 1, 2, 3), labels = c("Normal", "Mild", "Moderate", "Severe"))
  )

#-------------------------------------------------------------------------------------------------------------------

# Adding ui to the shiny app
ui <- dashboardPage(
# trial's title is given to the shiny dashboard header  
  dashboardHeader(title = "Digitalis Randomized, Double-blind, Multicenter Trial", titleWidth = 550), 
  
  
#Two side bar is created main and explore
  dashboardSidebar(
    sidebarMenu(
      menuItem("Main", tabName = "Main", icon = icon("dashboard")),
      menuItem("Explore", tabName = "Explore", icon = icon("chart-bar"))),

# File upload function added to the side bar      
    fileInput("file1", "Choose a File"), verbatimTextOutput("file1_contents"), 
    
# adding select input for placebo and digoxin under treatment label   
    selectInput(inputId = "Treatment", label = "Select Participants Treatment", choices = c("Placebo", "Digoxin"), multiple = TRUE),

# adding radio buttons for gender    
    radioButtons(inputId = "Sex", label = "Participant's Gender", choices = c("Male", "Female")),

# adding slider for age    
    sliderInput(inputId = "Age", "Participant's Age:", min = 18, max = 95, value = c(20, 30)),

# adding check boxes for various cardiovascular symptoms    
    checkboxGroupInput("checkGroup", label = h3("Cardiovascular Symptoms"), choices = list("ElevatedJVP" = 1, "Pedema" = 2, "Dyspnea_at_rest" = 3, "Dyspnea_on_exertion"= 4, "Action_limitation" = 5, "Pulmonary_congestion" = 6)),
    
    hr(), fluidRow(column(3, verbatimTextOutput("value"))),

# adding download button to download the data     
    downloadButton("downloadData", "Download DIG")), #download button for dig data

#----------------------------------------------------------------------------------------------------------------------

# Dashboard --> Main page, added 2 summary table  
  dashboardBody(
    tabItems(
      tabItem(tabName = "Main",
               fluidRow(

# adding patients demographics to the summary table                                 
                 box(width = 12, title = "Trial Data with Participant's Demographics", collapsible = TRUE, status = "warning", solidHeader = TRUE, dataTableOutput("table1")),
                 
# adding cv symptoms and death status to the cv conditions table                 
                 box(width = 12, title = "Cardiovascular conditions of Participants", collapsible = TRUE, status = "warning", solidHeader = TRUE, dataTableOutput("table2"))
      )
    ),

#---------------------------------------------------------------------------------------------------------------------

# Dashboard --> Explore page, added multiple plots and a table
    tabItem(tabName = "Explore",
            fluidRow(

# Adding all the numeric variables to this summary table to display their mean, median, sd, max, and min                            
              box(width = 6, title = "Summary", collapsible = TRUE, solidHeader = TRUE, status = "primary", tableOutput("SummaryTable")),
              
# Adding heat map             
              
              box(width = 6, title = "Interative Heatmap", collapsible = TRUE, solidHeader = TRUE, status = "primary", plotlyOutput("corrplot", height = "550px")),
              
# adding box plot to show correlation between CVD status and prescribed drug dose              
              
              box(width = 5, title = "Prescribed Dose", collapsible = TRUE, status = "warning", solidHeader = TRUE, plotlyOutput("plot1")),
              
# adding barplot to show correlation between the cardiovacular symptoms and severity and their count              
              
              box(width = 5, title = "Cardiovascular Symptoms", collapsible = TRUE, status = "primary", solidHeader = TRUE, plotlyOutput("barPlot")),
              
# adding CVD interactive network using visNetwork library, it shows status of cvd and how many patients are on which drugs
              
              box(width = 6, title = "CVD-Drug Network", collapsible = TRUE, status = "primary", solidHeader = TRUE, visNetworkOutput("CVDnetwork", height = "500px")),
              
# adding violin plot to show gender vise segregation of BP, Ejection fraction, and HR
              
              box(width = 5, title = "Violin Plot", collapsible = TRUE, status = "primary", solidHeader = TRUE, plotlyOutput("violinPlot")),
              
# adding stacked bar plot for each CV condition and death;alive count
              
              box(width = 5, title = "Death corelation", collapsible = TRUE, status = "primary", solidHeader = TRUE, plotlyOutput("stackedbarPlot"),  height = "500px")
              )
            )
    ) # closing tabitems parentheses
  ) #closing dashboardbody parentheses
) #closing dashboardPage parentheses
    
#---------------------------------------------------------------------------------------------------------------------

# Building server for shiny app
server <- function(input, output) {

# filtering reactive data
  df_sub <- reactive({
    df %>%
      filter(Treatment %in% input$Treatment) %>%
      filter(Sex == input$Sex) %>%
      filter(Age>= input$Age[1] & Age <= input$Age[2])
    })

  output$value <- renderPrint({input$checkGroup})

#--------------------------------------------------------------------------------    

# File input
 
  output$file1_contents <- renderPrint({print(input$file1)})
  
#----------------------------------------------------------------------------------  

# Download button
  
  output$downloadData <- downloadHandler(
    filename = "DIG.csv",
    content = function(file) {
      write.csv(DIG, file)
    })

#------------------------------------------------------------------------------------------------------------
  
# Data Table  1
  output$table1 <- renderDataTable({
    df_sub() %>%
      select(
        ID, Sex, Age, Race, BMI, Treatment, HTN, Diabetes, CVD, On_Digoxin, Prescribed_dose, Recommended_Dig_dose
      )
  })

#------------------------------------------------------------------------------------------------------------  
  
# Data Table  2
  output$table2 <- renderDataTable({
    df_sub() %>%
      select(
        ID, EF_percent, klevel, ElevatedJVP, Pedema, Dyspnea_at_rest, HTN, Diabetes, CVD, Prior_MI, Angina, Stroke, Death
      )
  })  
  
#---------------------------------------------------------------------------------------------------------  

# Summary Table  
  output$SummaryTable <- renderTable({
    st <- df_sub()
    req(nrow(st) > 0) # at-least 1 row

# checking everything should be numeric      
    num_df <- st[, sapply(st, is.numeric)]
    req(ncol(num_df) > 0) # at-least 1 column
      
    data.frame(
      Variable = names(num_df),
# applying function to each element of the df using sapply
      Mean = sapply(num_df, mean, na.rm = TRUE), 
      Median = sapply(num_df, median, na.rm = TRUE),
      SD = sapply(num_df, sd, na.rm = TRUE),
      Min = sapply(num_df, min, na.rm = TRUE),
      Max = sapply(num_df, max, na.rm = TRUE))
    
  })
 
#--------------------------------------------------------------------------------------------------------- 

# violin plot using plotly
  
  output$violinPlot <- renderPlotly({
    st <- df_sub() %>%
      select(Sex, EF_percent, Heart_rate, Diastolic_BP, Systolic_BP)
    
    st_vio <- st %>%
      pivot_longer(
        cols = -Sex,
        names_to = "Variable",
        values_to = "Value")
    
    fig <- plot_ly(
      data = st_vio,
      x = ~Variable,
      y = ~Value,
      color = ~Sex,
      type = "violin",
      split = ~Sex,
      box = list(visible = TRUE),
      meanline = list(visible = TRUE)
      )
    
    fig <- fig %>%
      layout(
        yaxis = list(zeroline = FALSE)
     #   violinmode = "group"
      )
}) 
      
  
#--------------------------------------------------------------------------------------------
 
# bar plot using plotly
output$barPlot <- renderPlotly({
  req(input$checkGroup)

# mapping
    vars_map <- c(
    "1" = "ElevatedJVP",
    "2" = "Pedema",
    "3" = "Dyspnea_at_rest",
    "4" = "Dyspnea_on_exertion",
    "5" = "Action_limitation",
    "6" = "Pulmonary_congestion"
  )

  selected_vars <- vars_map[input$checkGroup]

  st <- df_sub() %>% select(all_of(selected_vars))
  req(nrow(st) > 0)

# Convert to long format for easy analysis and plotting
  long_df <- tidyr::pivot_longer(st,
                                 cols = everything(),
                                 names_to = "Symptom",
                                 values_to = "Severity")

# Plot
  plot_ly(
    data = long_df,
    x = ~Symptom,
    color = ~Severity,
    type = "bar"
  ) %>%
    layout(
      barmode = "stack",
      title = "Severity Distribution of CV Symptoms",
      xaxis = list(title = "Symptom"),
      yaxis = list(title = "Count of Participants")
    )
})

  
#------------------------------------------------------------------------------------------------------------ 

# Boxplot  
  output$plot1 <- renderPlotly({
    st <- df_sub() %>%
      select(CVD, Prescribed_dose)
    
    req(nrow(st) > 0)
    
    plot_ly(data = st,
            x = ~CVD, y = ~Prescribed_dose, type = "bar", color = ~as.factor(Prescribed_dose)) %>%
      layout(barmode = "stack",
             title = "Prescribed dose for CVD patients",
             xaxis = list(title = "CVD Status"),
             yaxis = list(title = "Count"),
             legend = list(title = list(text = "Prescribed Dose")))
    
  })
    
#--------------------------------------------------------------------------------------------------

# heatmap 
  output$corrplot <- renderPlotly({
    st <- df_sub()
    
# rows should be more than one    
    req(nrow(st) > 1) 
    
#only numeric columns    
    num_df <- st[, sapply(st, is.numeric)] 

#need at least 2 numeric vars    
    req(ncol(num_df) > 1) 
    
    corr <- cor(num_df, use = "pairwise.complete.obs")
    
    plot_ly(
      x = colnames(corr),
      y = rownames(corr),
      z = corr,
      type = "heatmap",
      colorscale = list(
        c(0,1),
        c("blue", "red")),
      zmin = -1,
      zmax = 1) %>%
      layout(
        xaxis = list(tickangle = 45),
        yaxis = list(autorange = "reversed")
      )
  })
  
#---------------------------------------------------------------------------------------------

# stacked bar graph for diseases and death correlation
  
  output$stackedbarPlot <- renderPlotly({
    st <- df_sub() %>%
      select(CVD, WHF, MI, Unstable_Angina, Stroke, Supraventricular_Arrhythmia, Ventricular_Arrythmia, Coronary_Revasc, Other_CVD, Respiratory_infection, Other_noncardiac, HTN, Angina, Death)
    

# conforming death variable is a factor   
    st$Death <- factor(st$Death, levels = c("Alive", "Dead")) 
 

# Convert to long format for easy analysis and plotting           
  death_df <- tidyr::pivot_longer(
    st,
    cols = -Death,
    names_to = "Conditions",
    values_to = "Status"
  ) 
  
  death_df <- death_df %>% filter(Status == "Yes")
  
  req(nrow(death_df) > 0)

# creating new df for plot    
  summary_df <- death_df %>%
    group_by(Conditions, Death) %>%
    summarise(count = n(), .groups = "drop")
  
  req(nrow(summary_df) > 0)
  
# Plotly graph     
  plot_ly(data = summary_df,
          x = ~Conditions,
          y = ~count,
          type = "bar",
          color = ~Death,
          colors = c("Alive" = "green4", "Dead" = "red3"),
          text = ~count,
          textposition = "inside",
          hovertemplate = "Conditions: %{x}<br>Count: %{y}<extra></extra>"
          ) %>%
    layout(
         barmode = "stack",
         title = "Death vs Survivors",
         xaxis = list(title = "Cardiovascular conditions", tickangle = -45),
         yaxis = list(title = "Number of participants"),
         legend = list(title = list(text = "Outcome")))
    
  })
  
#-----------------------------------------------------------------------------------------------

#CVD network plot 
  
  output$CVDnetwork <- renderVisNetwork({
    st <- df_sub() %>%
      select(CVD, On_Digoxin, On_Ksparing, On_Diuretic, On_Ksupp, On_ACE, On_Nitrates, On_Hydralazine, On_Vasodilator)
    
    req(nrow(st) > 0)
    
    drug_cols <- c("On_Digoxin", "On_Ksparing", "On_Diuretic", "On_Ksupp", "On_ACE", "On_Nitrates", "On_Hydralazine", "On_Vasodilator")
    
    
    edges <- lapply(drug_cols, function(drug) {
      st %>%
        group_by(CVD) %>%
        summarise(count = sum(.data[[drug]] == "Yes")) %>%
        mutate(drug = drug)
    }) %>% bind_rows()
    
    edges <- edges %>% filter(count > 0) 
    
# df of network edges created    
    edges_df <- edges %>% 
      mutate(from = CVD, to = drug, value = count, title = paste0(count, "patients")) %>%
      select(from, to, value, title)

# df of node list created    
    nodes_df <- data.frame(
      id = c("Yes", "No", drug_cols),
      label = c("CVD", "Non-CVD", drug_cols),
      color = c("red", "green", rep("lightblue", length(drug_cols))),
      shape = "ellipse"
    )


# Interactive graph
    visNetwork(nodes_df, edges_df) %>%
      visEdges(smooth = TRUE) %>%
      visLayout(randomSeed = 123) %>%
      visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE)

  })
}
shinyApp(ui = ui, server = server)








```
